### PR TITLE
Adds support for getting and managing Issue Watchers

### LINKED ISSUE #72: Manage Watchers on an issue
Would be nice to be able to manage Watchers on an issue

### PR DESCRIPTION
**Pull request by ebekker**
Fixes #72

### CODE REVIEW

**Comment by ebekker** [comment]
@replicaJunction -- I'm a little confused with the AV results -- all the unit tests that failed were existing ones that I didn't touch nor the code that they're testing.

All of my changes are strictly new files except for the additions to the module manifest to export the new cmdlets.  Any ideas what's going on?

**Comment by ebekker** [comment]
Also, I have run the whole Pester suite on my local box and everything passes -- the only difference that I can see immediately is that I'm running PS/WMF 5.1 and AV is running 5.0.

**Comment by JohnLBevan** [comment]
I think the issue's caused by a different pull request somehow interfering with ours; those same objects were changed & are failing in #71 - https://github.com/replicaJunction/PSJira/pull/71/files.

That said, I tried to work around this by updating those same files to ensure that the  original versions were used, rather than those from another's pull request; with no luck: https://github.com/JohnLBevan/PSJira/commit/f6181460d3a4d090aa4ef03c0189f1abad4290e6

**Comment by JohnLBevan** [comment]
Apologies; my last comment's incorrect.
On looking deeper into this the issue is this line of code: `(Get-Member -InputObject $r).TypeName | Should Be 'PSJira.Project'` (and others like it).
Rather than returning the typename of the object passed in, it returns this value for each of the input object's members.  Will try to find time to fix soon...

**Comment by JohnLBevan** [comment]
FYI: Fixed issues in tests so that now all should work as expected.
Related issue: https://github.com/replicaJunction/PSJira/issues/76

**Comment by ebekker** [comment]
Ah, I take it your changes have not yet been merged into the parent project?

**Comment by JohnLBevan** [comment]
Sadly not yet; I don't have permissions, so need my pull request to be approved before those changes will be available; but anyone's free to copy them if they wish,

**Comment by lipkau** [comment]
Hi @ebekker 

sorry that this PR has been ignored for so long.
Can you please update the Test Cases and the file locations?

_by pushing to the branch in your fork, the PR will be extended automatically_

**Comment by lipkau** [comment]
@replicaJunction please review again

**Comment by ebekker** [comment]
Thanks for fixing/finishing this up!  Sorry I didn't have time to wrap it up myself!

**Comment by lipkau** [comment]
No problem

**Pull request merged**
