### PR TITLE
#74 - remove 50 user limit on Get-JiraUser; added pagination to pull …

### PR DESCRIPTION
**Pull request by JohnLBevan**
…back additional results when there are more than 50 matches

### CODE REVIEW

**Comment by JohnLBevan** [comment]
Hey @replicaJunction ,

Is there anything I need to do to improve this submission / have it merged?
I'm assuming it's just queued as you've not yet had a chance (in which case, fair enough), but wanted to check in case there's anything more I can do to have my pull request accepted?

Thanks in advance; and also for creating & sharing this awesome library.

JB

**Comment by aschi75** [comment]
Von: John Bevan [mailto:notifications@github.com]
Gesendet: Dienstag, 9. Mai 2017 20:56
An: replicaJunction/PSJira <PSJira@noreply.github.com>
Cc: Subscribed <subscribed@noreply.github.com>
Betreff: Re: [replicaJunction/PSJira] #74 - remove 50 user limit on Get-JiraUser; added pagination to pull … (#75)


Hey @replicaJunction<https://github.com/replicaJunction> ,

Is there anything I need to do to improve this submission / have it merged?
I'm assuming it's just queued as you've not yet had a chance (in which case, fair enough), but wanted to check in case there's anything more I can do to have my pull request accepted?

Thanks in advance; and also for creating & sharing this awesome library.

JB

**Comment by lipkau** [comment]
Hi @JohnLBevan 

sorry that this PR has been ignored for so long.
Can you please update the Test Cases and the file locations?

_by pushing to the branch in your fork, the PR will be extended automatically_

**Comment by JohnLBevan** [comment]
Hey @lipkau 

No worries / thanks for getting back to me.
I've now merged the latest changes from the DEV branch into my copy of the project & attempted to commit this request; but it's failing on the AppVeyor piece with: 

> Failure: AppVeyor was unable to build non-mergeable pull request

Sadly I'm not familiar enough with AppVeyor / GitHub to know what's required; so far as I can see all should be OK from a code perspective.  Are you able to offer any hints?  Apologies if it's something I've done incorrectly.

Thanks in advance,

JB

**Comment by JohnLBevan** [comment]
That's awesome; thank-you @lipkau; you're a true gentleman.

**Comment by lipkau** [comment]
I intent to no merge this PR. I prefer for the paging to be handled centrally.

I suggest to:
* [x] close this PR
* [x] continue this with #114 
* [ ] merge these changes with a new PR that `closes #114`

**Pull request closed without merging**
