### PR TITLE
Feature/Improve:Get-JiraComponent

### PR DESCRIPTION
**Pull request by lipkau**

### CODE REVIEW

**Comment by lipkau** [comment]
The UnitTest that failed in teh CI did not fail on my local computer.
Can you give me a hand, @replicaJunction ?
I gave you the according permissions in my fork

**Comment by JohnLBevan** [comment]
FYI: Resolved those errors under https://github.com/replicaJunction/PSJira/pull/75/commits/a59b170c9d74f454601954e9b00c89eb64b92026.  Hopefully if my pull request is accepted it should resolve for you too; or if you prefer you can grab the amended code from my version.

FYI: I saw these issues on my machine after installing the latest version of Pester.
`(Get-Module -Name 'Pester' -ListAvailable).Version` => `4, 0, 2, -1`

I suspect the logic has been altered so that the left side of the `| Should Be` was changed to handle an array as a single value rather than taking each value in the pipeline and comparing it; i.e. so n times TypeName is compared to a single TypeName, instead of comparing each value in the list of N TypeNames... Not sure though as I can't see any obvious changes for this in the Pester code base.

**Comment by lipkau** [comment]
thanks for the hint, @JohnLBevan 

I am not going to fix this in this PR. I will wait for it to be fixed (maybe merged from yours) and then merge it with this.
makes no sense to reinvent the wheel.

But since you brought it up:
I didn't put to much thought into this yet, but it appears to me that checking $...[0] is a bad practice.
What this library does, is to inject a value into the Object's TypeName property...
There is nothing keeping anyone from injecting more.
In my lib ([PsConfluence](https://github.com/lipkau/PsConfluence)) I declare the classes for the objects in order to check it with $....getType().
I know this is not applicable here. But I think checking it like this would be better (in the functions and in the UnitTests):
`$object.PSObject.TypeNames -contains "PSJira.Project"`

**Comment by JohnLBevan** [comment]
Completely agree.  It looks like Pester does have `Should Contain`; but that's referring to files rather than arrays.

I've submitted a new task related to refactoring the logic to a single function to make it more maintainable, and have put some examples of what can be done along with pros and cons of each approach, so that discussion can be had on that thread:  https://github.com/replicaJunction/PSJira/issues/79

**Pull request merged**
